### ISSUE TITLE
[ESC]u / [ESC]l

### ISSUE THREAD

**Issue by Shea690901** [mtxr/zsh-change-case#1]
Just a simple question:
You do know the default keybinding for [ESC]u and [ESC]l?

**Comment by mtxr** [comment]
What do you mean?

**Comment by Shea690901** [comment]
Default for '[ESC]u' is to change from cursor to end of word into uppercase and for '[ESC]l' to lowercase...

**Comment by mtxr** [comment]
You can unset and set the keybindings for whatever you want. So far I don't see a reason to change it yet
